// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package com.stone98.example.grpc.proto;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitude = 1;</code>
   * @return The latitude.
   */
  int getLatitude();

  /**
   * <code>int32 longitude = 2;</code>
   * @return The longitude.
   */
  int getLongitude();
}
