server:
  port: 8081
spring:
  application:
    name: springcloud-openfegin-producer
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: public
      config:
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: public
        server-addr: http://127.0.0.1:8848
        register-enable: true