server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/candyaaa/spring-cloud-config.git
          search-paths: #github上面的git仓库路径
            - spring-cloud-config
      label: main #读取分支

eureka:
  client:
    server-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false
    fetch-registry: false

