server:
  port: 8080
spring:
  application:
    name: springcloud-ribbon-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: public
      config:
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: public
        server-addr: http://127.0.0.1:8848
        register-enable: true